# Generated by Django 5.0.6 on 2024-09-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendoapp', '0002_alter_usuario_apellidos_alter_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='banos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estacionamientos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='habitaciones',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m2_construidos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m2_totales',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_arriendo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='arrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='arriendoapp.usuario'),
        ),
        migrations.AlterField(
            model_name='tipoinmueble',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
